## 
## jlink Stage
## 
FROM azul/zulu-openjdk-alpine:11 as jlinkStage

RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base,java.logging \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /jvm

##
## Final Stage
##
FROM alpine

COPY --from=jlinkStage /jvm /jvm
COPY --from=demoapp:jdk /demoapp.jar /

CMD ["/jvm/bin/java", "-jar", "/demoapp.jar"]
