FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu as stageBuild

RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base,java.logging,java.management \
         --strip-java-debug-attributes \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /jvm

FROM debian:buster-slim

COPY --from=stageBuild /jvm /jvm
COPY --from=demoapp:jdk /target/demoapp-1.0-SNAPSHOT-jar-with-dependencies.jar /demoapp.jar

CMD ["/jvm/bin/java", "-jar", "/demoapp.jar"]
