## 
## jlink Stage
## 
FROM azul/zulu-openjdk-alpine:11 as jlinkStage

RUN $JAVA_HOME/bin/jlink \
         --add-modules java.base,java.logging \
         --strip-java-debug-attributes \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /jvm

##
## Final Stage
##
FROM alpine:3.14

COPY --from=jlinkStage /jvm /jvm
COPY --from=demoapp:jdk /demoapp.jar /

CMD ["/jvm/bin/java", "-jar", "/demoapp.jar"]
